/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package www.examen2labp2_salvadormacias;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Apple
 */
public class principal extends javax.swing.JFrame {

    //fila 2 asiento 10
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        read_file();

    }

    File archivo = new File("./carros.txt");
    String ganador = "";
    boolean victoria = false;
    Carrera Carro1 = null;
    Carrera Carro2 = null;
    Thread proceso1 = null;
    Thread proceso2 = null;
    tiempo tiempo = null;
    Thread procesoTiempo = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame_partida = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        boton_crearCarro_partida = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_modelo1 = new javax.swing.JLabel();
        label_velocidad1 = new javax.swing.JLabel();
        label_marca2 = new javax.swing.JLabel();
        label_marca1 = new javax.swing.JLabel();
        label_velocidad2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        boton_iniciar_partida = new javax.swing.JButton();
        label_modelo2 = new javax.swing.JLabel();
        frame_progreso = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        label_tiempo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        label_carro1 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        label_carro2 = new javax.swing.JLabel();
        boton_iniciar_carrera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_marca = new javax.swing.JTextField();
        text_modelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spinner_velocidad = new javax.swing.JSpinner();
        boton_crear_carro = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Partida");

        boton_crearCarro_partida.setText("crear carro");
        boton_crearCarro_partida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_crearCarro_partidaMouseClicked(evt);
            }
        });

        jLabel6.setText("jugador 2");

        jLabel7.setText("jugador 1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jLabel8.setText("VS");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("Marca");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("Marca");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setText("Modelo");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel12.setText("Velocidad");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel13.setText("Modelo");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel14.setText("Velocidad");

        boton_iniciar_partida.setText("iniciar");
        boton_iniciar_partida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_iniciar_partidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frame_partidaLayout = new javax.swing.GroupLayout(frame_partida.getContentPane());
        frame_partida.getContentPane().setLayout(frame_partidaLayout);
        frame_partidaLayout.setHorizontalGroup(
            frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_partidaLayout.createSequentialGroup()
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_partidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125)
                        .addComponent(jLabel8)
                        .addGap(107, 107, 107)))
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(boton_crearCarro_partida)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_partidaLayout.createSequentialGroup()
                        .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_marca2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label_modelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frame_partidaLayout.createSequentialGroup()
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frame_partidaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addGap(134, 134, 134))
            .addGroup(frame_partidaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(label_velocidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frame_partidaLayout.createSequentialGroup()
                                .addComponent(label_velocidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(114, 114, 114))
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(boton_iniciar_partida, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame_partidaLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jLabel7)
                    .addContainerGap(509, Short.MAX_VALUE)))
        );
        frame_partidaLayout.setVerticalGroup(
            frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_partidaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_crearCarro_partida)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addComponent(label_marca2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_modelo2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)))
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_velocidad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addComponent(boton_iniciar_partida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86))
                    .addGroup(frame_partidaLayout.createSequentialGroup()
                        .addComponent(label_velocidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(frame_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frame_partidaLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(jLabel7)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel21.setText("TIEMPO");

        jLabel22.setText("PROGRESO");

        jProgressBar2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar2StateChanged(evt);
            }
        });

        boton_iniciar_carrera.setText("iniciar");
        boton_iniciar_carrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_iniciar_carreraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frame_progresoLayout = new javax.swing.GroupLayout(frame_progreso.getContentPane());
        frame_progreso.getContentPane().setLayout(frame_progresoLayout);
        frame_progresoLayout.setHorizontalGroup(
            frame_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_progresoLayout.createSequentialGroup()
                .addGroup(frame_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_progresoLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(frame_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_carro1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frame_progresoLayout.createSequentialGroup()
                                .addGroup(frame_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, frame_progresoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(frame_progresoLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(boton_iniciar_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frame_progresoLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(frame_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frame_progresoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(label_carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        frame_progresoLayout.setVerticalGroup(
            frame_progresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_progresoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(27, 27, 27)
                .addComponent(label_carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(label_carro1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(boton_iniciar_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Creacion de carros");

        jLabel3.setText("marca");

        jLabel4.setText("modelo");

        text_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_marcaActionPerformed(evt);
            }
        });

        text_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_modeloActionPerformed(evt);
            }
        });

        jLabel5.setText("velocidad");

        spinner_velocidad.setModel(new javax.swing.SpinnerNumberModel());

        boton_crear_carro.setText("crear");
        boton_crear_carro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_crear_carroMouseClicked(evt);
            }
        });
        boton_crear_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crear_carroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spinner_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_crear_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(text_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(text_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(spinner_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(boton_crear_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_marcaActionPerformed

    private void text_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_modeloActionPerformed

    private void boton_crear_carroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_crear_carroMouseClicked
        frame_partida.setVisible(true);
        frame_partida.pack();
        frame_partida.setLocationRelativeTo(null);
        lista.add(new carro(text_modelo.getText(), text_marca.getText(), (int) spinner_velocidad.getValue()));
        write_file();
        read_file();
        this.pack();
        this.setVisible(true);
        JOptionPane.showMessageDialog(this, "carro creado exitosamente...");

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_crear_carroMouseClicked

    private void boton_iniciar_partidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_iniciar_partidaMouseClicked
        this.setVisible(false);
        frame_progreso.pack();
        frame_progreso.setVisible(true);
        label_carro1.setText(((carro) jComboBox1.getSelectedItem()).getModelo());
        label_carro2.setText(((carro) jComboBox2.getSelectedItem()).getModelo());
        jProgressBar2.setValue(0);
        jProgressBar1.setValue(0);
        label_tiempo.setText(null);
        victoria = false;

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_iniciar_partidaMouseClicked

    private void boton_iniciar_carreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_iniciar_carreraMouseClicked
        carro temp1 = (carro) jComboBox1.getSelectedItem();
        carro temp2 = (carro) jComboBox2.getSelectedItem();

        //Carro1 = new tiempo(jProgressBar1, temp1);
        //Carro2 = new tiempo(jProgressBar2, temp2);
        proceso1 = new Thread(Carro1);
        proceso2 = new Thread(Carro2);
        proceso1.start();
        proceso2.start();

        tiempo = new tiempo(label_tiempo);
        procesoTiempo = new Thread(tiempo);
        procesoTiempo.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_boton_iniciar_carreraMouseClicked

    private void boton_crear_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crear_carroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_crear_carroActionPerformed

    private void boton_crearCarro_partidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_crearCarro_partidaMouseClicked


    }//GEN-LAST:event_boton_crearCarro_partidaMouseClicked

    private void jProgressBar2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar2StateChanged
        if (jProgressBar2.getValue() >= jProgressBar2.getMaximum() && !victoria) {

            ganador = label_carro1.getText();
            victoria = true;
            Carro1.setVive(false);
            Carro2.setVive(false);
            tiempo.setFlag(false);
            Carro1 = null;
            Carro2 = null;
            proceso1 = null;
            proceso2 = null;
            tiempo = null;
            procesoTiempo = null;

            if (jProgressBar2.getValue() == jProgressBar2.getValue()) {
                JOptionPane.showMessageDialog(this, "Fue un empate a los " + label_tiempo.getText());
            } else {

                JOptionPane.showMessageDialog(this, "El Jugador 1 ha ganado con " + ganador + " a los " + label_tiempo.getText());

            }
            frame_progreso.setVisible(false);
            this.pack();
            this.setVisible(true);

        }
        if (jProgressBar1.getValue() >= jProgressBar1.getMaximum() && !victoria) {
            ganador = label_carro2.getText();
            victoria = true;
            Carro1.setVive(false);
            Carro2.setVive(false);
            tiempo.setFlag(false);
            Carro1 = null;
            Carro2 = null;
            proceso1 = null;
            proceso2 = null;
            tiempo = null;
            procesoTiempo = null;
            if (jProgressBar1.getValue() == jProgressBar2.getValue()) {

            } else {

                JOptionPane.showMessageDialog(this, "El Jugador 2 ha ganado con " + ganador + " a los " + label_tiempo.getText());

            }
            frame_progreso.setVisible(false);
            this.pack();
            this.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar2StateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        carro temp = (carro) jComboBox1.getSelectedItem();
        label_marca1.setText(temp.getMarca());
        label_modelo2.setText(temp.getModelo());
        label_velocidad1.setText("" + temp.getVelocidad());

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        carro temp = (carro) jComboBox2.getSelectedItem();
        label_marca2.setText(temp.getMarca());
        label_modelo2.setText(temp.getModelo());
        label_velocidad2.setText("" + temp.getVelocidad());

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    public void write_file() {

        FileOutputStream fos = null;
        ObjectOutputStream oos = null;

        try {

            fos = new FileOutputStream(archivo, false);
            oos = new ObjectOutputStream(fos);

            for (carro c : lista) {

                oos.writeObject(c);

            }

            oos.flush();

            oos.close();
            fos.close();

        } catch (IOException e) {

        }
    }

    public void read_file() {

        FileInputStream fis = null;
        ObjectInputStream ois = null;

        try {

            fis = new FileInputStream(archivo);
            ois = new ObjectInputStream(fis);
            lista = new ArrayList();

            carro temp;
            while ((temp = (carro) ois.readObject()) != null) {

                lista.add(temp);
                label_marca1.setText(lista.get(0).getMarca());
                label_marca2.setText(lista.get(0).getMarca());
                label_modelo1.setText(lista.get(0).getModelo());
                label_modelo2.setText(lista.get(0).getModelo());
                label_velocidad1.setText("" + lista.get(0).getVelocidad());
                label_velocidad2.setText("" + lista.get(0).getVelocidad());

            }

            for (carro carro : lista) {
                System.out.println(carro.toString());
            }

            fis.close();
            ois.close();

        } catch (IOException e) {

        } catch (ClassNotFoundException e) {
        }

        update_cb();
    }

    public void update_cb() {

        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();

        for (carro c : lista) {

            modelo1.addElement(c);
            modelo2.addElement(c);

        }

        jComboBox1.setModel(modelo1);
        jComboBox2.setModel(modelo2);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_crearCarro_partida;
    private javax.swing.JButton boton_crear_carro;
    private javax.swing.JButton boton_iniciar_carrera;
    private javax.swing.JButton boton_iniciar_partida;
    private javax.swing.JFrame frame_partida;
    private javax.swing.JFrame frame_progreso;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel label_carro1;
    private javax.swing.JLabel label_carro2;
    private javax.swing.JLabel label_marca1;
    private javax.swing.JLabel label_marca2;
    private javax.swing.JLabel label_modelo1;
    private javax.swing.JLabel label_modelo2;
    private javax.swing.JLabel label_tiempo;
    private javax.swing.JLabel label_velocidad1;
    private javax.swing.JLabel label_velocidad2;
    private javax.swing.JSpinner spinner_velocidad;
    private javax.swing.JTextField text_marca;
    private javax.swing.JTextField text_modelo;
    // End of variables declaration//GEN-END:variables
   public ArrayList<carro> lista = new ArrayList<>();

}
